-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO friend (name) VALUES ('Peter');
-- INSERT INTO friend (name) VALUES ('Paul');
-- INSERT INTO friend (name) VALUES ('Mary');
